[package]
name = "blockchain-rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "lib"
path = "src/lib/mod.rs"

[dependencies]
chrono = "0.4.38"
sha2 = "0.10.8"
num = "0.4.2"
sled = "0.34.7"

serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
